services:
  api:
    build: ./back
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      # 💡 핵심: Docker 안에서 Mac 본체의 Ollama(포트 11434)로 접속하는 주소
      - OLLAMA_URL=http://host.docker.internal:11434
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    volumes:
      - ./back:/app

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama
    container_name: ollama_llm
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: